Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -25,7 +25,7 @@ jobs:
           echo "aurore_frontend/lib directory contents:"
           ls -la aurore_frontend/lib
           echo "Contents of aurore_frontend/lib/main.dart:"
-          cat aurore_frontend/lib/main.dart
+          cat aurore_frontend/lib/main.dart || echo "main.dart not found"
 
       - name: Get dependencies
         run: flutter pub get
@@ -40,7 +40,7 @@ jobs:
         working-directory: aurore_frontend
 
       - name: Upload APK artifact
-        uses: actions/upload-artifact@v4
+        uses: actions/upload-artifact@834a144ee995460fba8ed112a2d6f634b217dcc # v4.4.3
         with:
           name: app-release.apk
           path: aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
