Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,16 +38,16 @@ jobs:
         run: |
           pwd
           ls -la .
-          ls -la ./aurore_frontend || { echo "Error: aurore_frontend directory not found"; exit 1; }
+          ls -la ./aurore-FRONTEND || { echo "Error: aurore-FRONTEND directory not found"; exit 1; }
 
       # Get Flutter dependencies
       - name: Install dependencies
-        working-directory: ./aurore_frontend
+        working-directory: ./aurore-FRONTEND
         run: flutter pub get
 
       # Build the APK
       - name: Build APK
-        working-directory: ./aurore_frontend
+        working-directory: ./aurore-FRONTEND
         run: |
           flutter build apk --release
           ls -la build/app/outputs/flutter-apk/ || { echo "Error: APK build failed or output not found"; exit 1; }
@@ -57,4 +57,4 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: app-release.apk
-          path: aurore-FRONTEND/aurore_frontend/build/app/outputs/flutter-apk/app-release.apk
+          path: aurore-FRONTEND/aurore-FRONTEND/build/app/outputs/flutter-apk/app-release.apk
